services:
  - type: web
    name: flask-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:5005"  # Utiliser 0.0.0.0 pour Render
    envVars:
      - key: FLASK_ENV
        value: production
    dockerfilePath: ./Dockerfile  # Assurez-vous que ce chemin est correct

