services:
  - type: web
    name: flask-api
    env: python
    plan: free
    buildCommand: "docker build -t flask-api ."
    startCommand: "docker run -p 5005:5005 flask-api"
    envVars:
      - key: FLASK_ENV
        value: production

