name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déclenche le workflow uniquement sur la branche "main"
    paths:
      - 'tests/**'  # Ne déclenche le workflow que si des fichiers dans le dossier tests sont modifiés

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurez Git pour utiliser Heroku comme distant
      - name: Set up Heroku remote
        run: git remote add heroku https://git.heroku.com/project-science-free.git

      # Authentifiez-vous auprès de Heroku en utilisant votre clé API
      - name: Authenticate with Heroku
        run: |
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Tirez les modifications du dépôt distant Heroku pour éviter les conflits
      - name: Pull changes from Heroku
        run: git pull heroku main --allow-unrelated-histories || true

      # Poussez les changements locaux vers Heroku
      - name: Push changes to Heroku
        run: git push heroku main --force

