name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déploiement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Heroku authentication
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc

    - name: Deploy to Heroku
      run: git push https://git.heroku.com/project-science-free.git main

