name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère le code de votre dépôt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Vous pouvez ajuster la version selon votre besoin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances définies dans requirements.txt

      - name: Login to Heroku
        run: echo "$HEROKU_API_KEY" | heroku auth:token  # Utilise la clé API Heroku secrète

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/your-app-name.git  # Remplacez 'your-app-name' par le nom de votre app Heroku
          git push heroku main  # Pousse le code sur Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Utilise le secret Heroku API Key de GitHub


